services:
  - type: web
    name: sam-filter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_simple.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000